### ISSUE TITLE
Can't install on Raspbian/jessie

### ISSUE THREAD

**Issue by atomicptr** [Silvenga/btsync-deb#2]
I tried installing the package on raspbian/jessie and got this:

```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
```

The 2.0 package from tuxpoldo worked fine on the Rasberry Pi, I'm not sure what needs to be changed since I don't know much about debs.

**Comment by Silvenga** [comment]
From the stacktrace it looks like Raspbian's `add-apt-repository` command is broken. 

Try the legacy method of adding repositories:

```
echo "deb http://deb.silvenga.com/btsync any main" > /etc/apt/sources.list.d/silvenga-btsync-deb.list
apt-get update
apt-get install btsync
```

If that doesn't fix your issue could you provide the full set of commands used and the output of?

```
tail /etc/apt/sources.list
```

**Comment by atomicptr** [comment]
Yes, the problem was related to add-apt-repository probably, thanks for the help!
