### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HTTPMessage'

### ISSUE THREAD

**Issue by levin-kelevra** [Silvenga/btsync-deb#5]
BitTorrent Sync forked to background. pid = 2430. default port = 8888
Traceback (most recent call last):
  File "/usr/lib/btsync-gui/btsyncstatus.py", line 162, in btsync_connect
    version = self.agent.get_version()
  File "/usr/lib/btsync-gui/btsyncapi.py", line 372, in get_version
    return self._request(params,throw_exceptions)
  File "/usr/lib/btsync-gui/btsyncapi.py", line 477, in _request
    self.response = requests.get(self.urlroot, params=params, auth=self.auth)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 388, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/response.py", line 49, in assert_header_parsing
    if not isinstance(headers, httplib.HTTPMessage):
AttributeError: 'module' object has no attribute 'HTTPMessage'

**Comment by levin-kelevra** [comment]
Hmm. sorry, after upgrade requests module it works.

**Comment by Silvenga** [comment]
Sweet! So no issue?

**Comment by levin-kelevra** [comment]
No issue )
